interface pageProps {}
import VideoStats from "@/components/video-stats";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/z2nFmyKlblf
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";
import { ChartPieIcon } from "@heroicons/react/24/solid";

export default function page() {
  return (
    <div className="flex justify-center items-center pt-16 px-6 h-full">
      <Card className="w-full max-w-sm ">
        <CardHeader className="flex flex-col items-center space-y-1">
          <ChartPieIcon className="h-6 w-6" />
          <CardTitle className="text-sm">Analytics</CardTitle>
        </CardHeader>
        <CardContent className="text-center">
          <p className="text-sm">No video with the given ID is found</p>
        </CardContent>
      </Card>
    </div>
  );
}
