/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/z2nFmyKlblf
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";
import { ChartPieIcon } from "@heroicons/react/24/solid";

export function NoStats() {
  return (
    <Card className="w-full max-w-sm">
      <CardHeader className="flex flex-col items-center space-y-1">
        <ChartPieIcon className="h-6 w-6" />
        <CardTitle className="text-sm">Analytics</CardTitle>
      </CardHeader>
      <CardContent className="text-center">
        <p className="text-sm">
          No analytics can be given unless a video ID is provided.
        </p>
      </CardContent>
    </Card>
  );
}
